"""add_duration_seconds_to_daily_goals

Revision ID: 052f2eda1426
Revises: 9b80e17a00f7
Create Date: 2026-06-09 01:34:57.459479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052f2eda1426'
down_revision: Union[str, None] = '9b80e17a00f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with server default 0 so existing rows are backfilled, then drop the default
    op.add_column('daily_goals', sa.Column('duration_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('daily_goals', 'duration_seconds', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_goals', 'duration_seconds')
    # ### end Alembic commands ###
