"""remove_duration_seconds_from_daily_goals

Revision ID: ddaf4dea18e2
Revises: 052f2eda1426
Create Date: 2026-06-09 01:44:02.368653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaf4dea18e2'
down_revision: Union[str, None] = '052f2eda1426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_goals', 'duration_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_goals', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
